In [1]:
import pandas as pd

In [2]:
lien_df = pd.read_csv('../data/lien_df1_18_01_23.csv', sep=';')

In [3]:
lien_df

asset_id   views publication_date                      contact_name  \
0    814114.0  1535.0   15 ноября 2022            Контактный Центр Банка   
1    641505.0  2311.0    31 марта 2022        Гаас Александра Георгиевна   
2    169347.0   466.0   18 апреля 2022            Брюнель Ева Жисленовна   
3    899895.0  1286.0     25 июня 2022  Плесняев Александр Александрович   
4    269183.0  1057.0     17 июня 2022         Беликин Иван Владимирович   
..        ...     ...              ...                               ...   
827  691104.0   269.0      20 мая 2021            Коваленко Александр Ан   
828  630263.0   279.0      20 мая 2021            Коваленко Александр Ан   
829  177552.0   281.0      20 мая 2021            Коваленко Александр Ан   
830  841885.0   610.0      11 мая 2021          Нуриев Эдуард Рамзилович   
831  419254.0   461.0   22 апреля 2021        Самойленко Денис Сергеевич   

                          seller_name    square  price_value  \
0                      Банк ВТБ (ПАО)       NaN   48700000.0   
1                     Физическое лицо   25111.0  145500000.0   
2                     Физическое лицо   50574.0    4500000.0   
3    Плесняев Александр Александрович  504500.0   23450000.0   
4           Беликин Иван Владимирович   10000.0  320000000.0   
..                                ...       ...          ...   
827               АО "Россельхозбанк"    1527.0   10709963.0   
828               АО "Россельхозбанк"    1321.0    9265136.0   
829               АО "Россельхозбанк"    1676.0   11755032.0   
830               АО "Россельхозбанк"  150100.0     226651.0   
831                      ПАО Сбербанк   10000.0    8270000.0   

                           cadastral_geocode  \
0                                        NaN   
1     [51.94720028246027, 84.88831594503662]   
2     [56.77190698765615, 38.88962726762723]   
3    [55.73199800626753, 35.340751735565306]   
4      [55.7008175028533, 37.02131098410721]   
..                                       ...   
827   [56.21913602478085, 38.82900562858026]   
828  [56.220926330893064, 38.83048310378695]   
829    [56.21983629294916, 38.8300820194728]   
830  [55.822853130025955, 52.73092958759532]   
831   [57.14073651577907, 33.14393000643601]   

                              region_geocode  shown_by_days   distance  \
0                   [55.6711507, 37.2727963]      64.884407        NaN   
1                   [51.9931851, 84.9819571]     293.884407   8.221511   
2           [56.80208355, 38.64899133747492]     275.884407  15.086412   
3                    [55.506478, 36.0213092]     207.884407  49.688507   
4                   [55.6711507, 37.2727963]     215.884407  16.159018   
..                                       ...            ...        ...   
827          [56.1345574, 38.85192758087219]     608.884408   9.524407   
828          [56.1345574, 38.85192758087219]     608.884408   9.708539   
829          [56.1345574, 38.85192758087219]     608.884408   9.591824   
830  [55.682141200000004, 52.09069161386946]     617.884408  43.145711   
831                 [57.1557583, 33.1013213]     636.884408   3.074139   

     region_square  population region_capital     grp  criminality  \
0          44329.0   8542257.0         Москва  4201.8         72.9   
1         167996.0   2154932.0        Барнаул   550.0        130.8   
2          36177.0   1205637.0      Ярославль   560.6        105.1   
3          44329.0   8542257.0         Москва  4201.8         72.9   
4          44329.0   8542257.0         Москва  4201.8         72.9   
..             ...         ...            ...     ...          ...   
827        29084.0   1342235.0       Владимир   440.5         91.1   
828        29084.0   1342235.0       Владимир   440.5         91.1   
829        29084.0   1342235.0       Владимир   440.5         91.1   
830        67847.0   4000084.0         Казань  2469.2        102.1   
831        84201.0   1226038.0          Тверь   441.7        130.5   

       km_to_msk

In [4]:
selected_df = lien_df[['views', 'contact_name', 'seller_name', 'square', 'shown_by_days', 'distance', 'region_square', 'region_capital',
                       'grp', 'criminality', 'km_to_msk', 'km_to_region_capital', 'price_value']].copy()

In [5]:
selected_df.dtypes

views                   float64
contact_name             object
seller_name              object
square                  float64
shown_by_days           float64
distance                float64
region_square           float64
region_capital           object
grp                     float64
criminality             float64
km_to_msk               float64
km_to_region_capital    float64
price_value             float64
dtype: object

In [6]:
from sklearn.preprocessing import *

In [9]:
def one_hot_encoder_two(data,feature,keep_first=True):

    one_hot_cols = pd.get_dummies(data[feature])

    for col in one_hot_cols.columns:
        one_hot_cols.rename({col:f'{feature}_'+col},axis=1,inplace=True)

    new_data = pd.concat([data,one_hot_cols],axis=1)
    new_data.drop(feature,axis=1,inplace=True)

    if keep_first == False:
        new_data=new_data.iloc[:,1:]

    return new_data

In [10]:
selected_df

views                      contact_name  \
0    1535.0            Контактный Центр Банка   
1    2311.0        Гаас Александра Георгиевна   
2     466.0            Брюнель Ева Жисленовна   
3    1286.0  Плесняев Александр Александрович   
4    1057.0         Беликин Иван Владимирович   
..      ...                               ...   
827   269.0            Коваленко Александр Ан   
828   279.0            Коваленко Александр Ан   
829   281.0            Коваленко Александр Ан   
830   610.0          Нуриев Эдуард Рамзилович   
831   461.0        Самойленко Денис Сергеевич   

                          seller_name    square  shown_by_days   distance  \
0                      Банк ВТБ (ПАО)       NaN      64.884407        NaN   
1                     Физическое лицо   25111.0     293.884407   8.221511   
2                     Физическое лицо   50574.0     275.884407  15.086412   
3    Плесняев Александр Александрович  504500.0     207.884407  49.688507   
4           Беликин Иван Владимирович   10000.0     215.884407  16.159018   
..                                ...       ...            ...        ...   
827               АО "Россельхозбанк"    1527.0     608.884408   9.524407   
828               АО "Россельхозбанк"    1321.0     608.884408   9.708539   
829               АО "Россельхозбанк"    1676.0     608.884408   9.591824   
830               АО "Россельхозбанк"  150100.0     617.884408  43.145711   
831                      ПАО Сбербанк   10000.0     636.884408   3.074139   

     region_square region_capital     grp  criminality    km_to_msk  \
0          44329.0         Москва  4201.8         72.9    23.785924   
1         167996.0        Барнаул   550.0        130.8  3077.808288   
2          36177.0      Ярославль   560.6        105.1   137.376612   
3          44329.0         Москва  4201.8         72.9   142.859455   
4          44329.0         Москва  4201.8         72.9    37.925763   
..             ...            ...     ...          ...          ...   
827        29084.0       Владимир   440.5         91.1    91.247107   
828        29084.0       Владимир   440.5         91.1    91.433379   
829        29084.0       Владимир   440.5         91.1    91.345769   
830        67847.0         Казань  2469.2        102.1   946.305150   
831        84201.0          Тверь   441.7        130.5   315.461761   

     km_to_region_capital  price_value  
0                     NaN   48700000.0  
1              172.971129  145500000.0  
2              112.852414    4500000.0  
3              143.008314   23450000.0  
4               37.865816  320000000.0  
..                    ...          ...  
827             98.556292   10709963.0  
828             98.483280    9265136.0  
829             98.496885   11755032.0  
830            226.197191     226651.0  
831            170.094175    8270000.0  

[832 rows x 13 columns]

In [7]:
selected_df = selected_df.dropna()

In [16]:
le = LabelEncoder()
label_encoded_df = selected_df[['contact_name', 'seller_name', 'region_capital']].copy()
for col in label_encoded_df.select_dtypes(include='O').columns:
    label_encoded_df[col]=le.fit_transform(label_encoded_df[col])

In [10]:
label_encoded_df

contact_name  seller_name  region_capital
1              18           51               1
2              13           51              52
3              76           44              26
4               7            7              26
5              73           42              36
..            ...          ...             ...
827            51            2               6
828            51            2               6
829            51            2               6
830            70            2              15
831            80           42              43

[300 rows x 3 columns]

In [11]:
filled_df = pd.concat([selected_df[list(set(selected_df.columns) - set(['contact_name', 'seller_name', 'region_capital', 'price_value']))], label_encoded_df], axis=1)

In [12]:
filled_df.shape

(300, 12)

In [13]:
train_df = filled_df[:270]
test_df = filled_df[270:]

In [17]:
regression = LinearRegression()

NameError: name 'LinearRegression' is not defined

In [53]:
model = regression.fit(train_df.fillna(0), selected_df['price_value'][:270].fillna(0))

In [54]:
model.coef_

array([-1.45291902e+04,  3.38987306e+04, -2.76730604e+05,  1.62726439e+04,
        3.86170728e+03, -3.65365828e+04, -1.47677321e+04, -1.55207201e+01,
        4.99414587e-01, -1.80361172e+05,  3.32094599e+05, -5.55180263e+04])

In [56]:
model.predict(train_df[154:155].fillna(0))[0]

19780429.345412

In [45]:
train_df[154:155]

views  shown_by_days  criminality     grp    km_to_msk  \
154  145.0      64.884408        119.0  1259.4  1718.489257   

     km_to_region_capital  distance  region_square  square  contact_name  \
154                   NaN       NaN      1464173.0     NaN            69   

     seller_name  region_capital  
154           12              54

In [55]:
selected_df[154:155]

views                 contact_name   seller_name  square  shown_by_days  \
626  189.0  Сорокина Валерия Валерьевна  ПАО Сбербанк   200.0     195.884408   

      distance  region_square region_capital     grp  criminality  \
626  11.418301       142947.0            Уфа  1673.7         96.2   

       km_to_msk  km_to_region_capital  price_value  
626  1173.106583             80.622672      25680.0

In [27]:
from sklearn.linear_model import LinearRegression

In [31]:
train_df

views  shown_by_days  criminality     grp    km_to_msk  \
0    1535.0      64.884407         72.9  4201.8    23.785924   
1    2311.0     293.884407        130.8   550.0  3077.808288   
2     466.0     275.884407        105.1   560.6   137.376612   
3    1286.0     207.884407         72.9  4201.8   142.859455   
4    1057.0     215.884407         72.9  4201.8    37.925763   
..      ...            ...          ...     ...          ...   
695   761.0     351.884408         86.0  4193.5   661.697638   
696   403.0     357.884408         64.6   383.1   211.107380   
697   290.0     357.884408        130.8   550.0  2944.551449   
698   344.0     359.884408        122.5  1318.5  1221.029232   
699   313.0     359.884408        122.5  1318.5  1221.092906   

     km_to_region_capital   distance  region_square    square  contact_name  \
0                     NaN        NaN        44329.0       NaN            69   
1              172.971129   8.221511       167996.0   25111.0            24   
2              112.852414  15.086412        36177.0   50574.0            18   
3              143.008314  49.688507        44329.0  504500.0           112   
4               37.865816  16.159018        44329.0   10000.0            10   
..                    ...        ...            ...       ...           ...   
695                   NaN        NaN         1403.0    1100.0           121   
696             28.050180  28.231895        39605.0     660.0           159   
697                   NaN        NaN       167996.0    1700.0            22   
698             91.532742  17.631267       160236.0  548800.0            41   
699             91.541580  17.622324       160236.0  557200.0            41   

     seller_name  region_capital  
0             12              33  
1             75               2  
2             75              63  
3             65              33  
4             13              33  
..           ...             ...  
695           82              46  
696           75              44  
697           75               2  
698           62              40  
699           62              40  

[700 rows x 12 columns]

In [ ]:
# todo необходимо проверить кодирование категориальных данных => ок
# todo необходимо сделать шкалирование => не помогает
# todo необходимо написать нормальную функцию оценки

In [57]:
from sklearn.preprocessing import StandardScaler
stdsc = StandardScaler()

In [58]:
X_std = stdsc.fit_transform(train_df)

In [72]:
Y_std = stdsc.fit_transform(np.array(selected_df['price_value'][:270]).reshape(-1,1))

In [73]:
Y_std

array([[ 1.90639225e+00],
       [-2.48223247e-01],
       [ 4.13509630e-02],
       [ 4.57291994e+00],
       [-3.14909361e-01],
       [-3.15159969e-01],
       [-3.14909361e-01],
       [-3.15410576e-01],
       [-3.15159969e-01],
       [-3.15159969e-01],
       [-3.15159969e-01],
       [ 3.18394785e-01],
       [-3.15161099e-01],
       [-3.10410585e-01],
       [-3.15873590e-01],
       [-2.67171639e-01],
       [-3.15387869e-01],
       [-3.07860483e-01],
       [-3.14076029e-01],
       [-3.15079698e-01],
       [-3.10731821e-01],
       [-3.05155814e-01],
       [-3.15891040e-01],
       [-2.60448016e-01],
       [-3.16664639e-01],
       [ 7.32349291e+00],
       [-3.12403283e-01],
       [-1.76402731e-01],
       [-3.12619891e-01],
       [-2.92996463e-01],
       [-3.13388447e-01],
       [ 1.41441257e-01],
       [-3.16345771e-01],
       [-3.15673409e-01],
       [-3.15749814e-01],
       [-3.12988544e-01],
       [-3.16483300e-01],
       [-3.12036540e-01],
       [-1.8

In [74]:
model = regression.fit(X_std, Y_std)

In [81]:
model.predict(X_test[10:11])[0]

array([-0.16603159])

In [77]:
X_test = stdsc.fit_transform(test_df)

In [78]:
Y_test = stdsc.fit_transform(np.array(selected_df['price_value'][270:]).reshape(-1,1))

In [82]:
Y_test[10:11]

array([[-1.84000847]])

In [94]:
model.predict(X_test[98:99])

ValueError: Found array with 0 sample(s) (shape=(0, 12)) while a minimum of 1 is required by LinearRegression.

In [97]:
stdsc.inverse_transform(model.predict(X_test[21:22]))[0][0]

8308045.976460408

In [98]:
stdsc.inverse_transform(Y_test[21:22])[0][0]

8297248.0

In [123]:
delta_dict = {}
for i in range(28):
    try:
        delta_dict[i] = abs(stdsc.inverse_transform(model.predict(X_test[i:i+1]))[0][0] / stdsc.inverse_transform(Y_test[i:i+1])[0][0])
    except:
        pass

In [124]:
that_df = pd.DataFrame(data=[delta_dict]).T

In [125]:
that_df.median()[0]  # да в целом не все так плохо! можно жить ахах

0.7805488106367666

In [126]:
that_df.min()[0]

0.6289236242901495

In [127]:
that_df.max()[0]

75.27730850018717

In [128]:
that_df

0
0    0.716408
1    0.763133
2    0.707759
3    0.687951
4    0.698291
5    0.628924
6    0.675230
7    0.671724
8    0.703144
9    0.668059
10   6.631709
11   0.807570
12   0.757733
13   7.882117
14   0.717845
15   0.665688
16   0.848414
17   0.840192
18   8.555488
19  75.277309
20   0.855383
21   1.001301
22   9.711783
23   0.852194
24   0.797965
25   0.811726
26   0.934210
27   0.735920

In [129]:
# нужно нормально оценить как то эти результаты

In [96]:
X_test

array([[-0.0769971 , -0.53433326, -0.34575576, -0.30784083, -0.35824391,
        -0.0428251 , -0.25012761, -0.35013769, -0.24729777, -0.23126176,
        -0.33333333, -0.36021694],
       [-0.08975905, -0.53433326, -0.34575576, -0.30784083, -0.35835803,
        -0.04225793, -0.25296048, -0.35013769, -0.25079504, -0.23126176,
        -0.33333333, -0.36021694],
       [ 0.2292897 , -0.53433326, -0.34575576, -0.30784083, -0.35847255,
        -0.04168745, -0.25578835, -0.35013769, -0.24722566, -0.23126176,
        -0.33333333, -0.36021694],
       [ 0.2803375 , -0.53433326, -0.34575576, -0.30784083, -0.3585927 ,
        -0.04108719, -0.25873664, -0.35013769, -0.24567532, -0.23126176,
        -0.33333333, -0.36021694],
       [-0.08975905, -0.53433326, -0.34575576, -0.30784083, -0.35788561,
        -0.04365986, -0.23519724, -0.35013769, -0.24578349, -0.23126176,
        -0.33333333, -0.36021694],
       [-0.06423515, -0.53433326, -0.34575576, -0.30784083, -0.35800858,
        -0.04305551, -

In [2]:
X_test[10:11]

NameError: name 'X_test' is not defined

In [1]:
# у нас есть дата лик в виде цены на квадратный метр
# хотя не, вроде все ровно, мы убрали его ранее

### 22.1.23 review of what we got

In [8]:
from models_functions import encode_features, make_regression

In [9]:
from sklearn import metrics

In [11]:
lien_df = pd.read_csv('../data/lien_df1_18_01_23.csv', sep=';')

In [12]:
selected_df = lien_df[['views', 'contact_name', 'seller_name', 'square', 'shown_by_days', 'distance', 'region_square', 'region_capital', 'grp', 'criminality', 'km_to_msk', 'km_to_region_capital', 'price_value']].copy()

In [13]:
selected_df = selected_df.dropna()  # пока поработаем без null

In [14]:
# categorical features
cat_features_list = ['contact_name', 'seller_name', 'region_capital']

In [16]:
label_encoded_df = encode_features(selected_df)

In [17]:
model, X_test_std, Y_test_std, stdsc = make_regression(label_encoded_df, 'price_value')

In [18]:
model.predict(X_test_std[1:2])

array([[-0.20824906]])

In [19]:
# todo какие оценки нам надо сделать?: MAPE, RMSE

In [22]:
# давай протестируем со шкалированными данными и без

In [19]:
Y_pred_std = model.predict(X_test_std)

In [20]:
metrics.mean_absolute_percentage_error(Y_test_std, Y_pred_std)  # 127 %? .. 600%??

6.215795318267291

In [21]:
metrics.mean_absolute_error(Y_test_std, Y_pred_std)

0.609374526650863

In [22]:
0.609374526650863/ Y_test_std.max()

0.10951284082445209

In [38]:
# This is known as a scale-dependent accuracy measure and, therefore, cannot be used to make comparisons between series using different scales.

4.374120554533135

In [30]:
# It is for example not changed by a global scaling of the target variable.
# todo попробовать разные метрики добавить (например, MedError)

In [ ]:
# todo надо проделать для absolute values, надо сделать функцию для возврата absolute_error

In [11]:
# todo добавить фичу средняя цена за квадрат в регионе

In [10]:
# todo попробовать в encode_features все спрятать

views                      contact_name  \
1    2311.0        Гаас Александра Георгиевна   
2     466.0            Брюнель Ева Жисленовна   
3    1286.0  Плесняев Александр Александрович   
4    1057.0         Беликин Иван Владимирович   
5     812.0                   Остроухова Алла   
..      ...                               ...   
827   269.0            Коваленко Александр Ан   
828   279.0            Коваленко Александр Ан   
829   281.0            Коваленко Александр Ан   
830   610.0          Нуриев Эдуард Рамзилович   
831   461.0        Самойленко Денис Сергеевич   

                          seller_name    square  shown_by_days   distance  \
1                     Физическое лицо   25111.0     293.884407   8.221511   
2                     Физическое лицо   50574.0     275.884407  15.086412   
3    Плесняев Александр Александрович  504500.0     207.884407  49.688507   
4           Беликин Иван Владимирович   10000.0     215.884407  16.159018   
5                        ПАО Сбербанк    2400.0     674.884407   8.780511   
..                                ...       ...            ...        ...   
827               АО "Россельхозбанк"    1527.0     608.884408   9.524407   
828               АО "Россельхозбанк"    1321.0     608.884408   9.708539   
829               АО "Россельхозбанк"    1676.0     608.884408   9.591824   
830               АО "Россельхозбанк"  150100.0     617.884408  43.145711   
831                      ПАО Сбербанк   10000.0     636.884408   3.074139   

     region_square  region_capital     grp  criminality    km_to_msk  \
1         167996.0         Барнаул   550.0        130.8  3077.808288   
2          36177.0       Ярославль   560.6        105.1   137.376612   
3          44329.0          Москва  4201.8         72.9   142.859455   
4          44329.0          Москва  4201.8         72.9    37.925763   
5         100967.0  Ростов-на-Дону  1446.2        104.8   945.986855   
..             ...             ...     ...          ...          ...   
827        29084.0        Владимир   440.5         91.1    91.247107   
828        29084.0        Владимир   440.5         91.1    91.433379   
829        29084.0        Владимир   440.5         91.1    91.345769   
830        67847.0          Казань  2469.2        102.1   946.305150   
831        84201.0           Тверь   441.7        130.5   315.461761   

     km_to_region_capital  price_value  
1              172.971129  145500000.0  
2              112.852414    4500000.0  
3              143.008314   23450000.0  
4               37.865816  320000000.0  
5               17.188847     136000.0  
..                    ...          ...  
827             98.556292   10709963.0  
828             98.483280    9265136.0  
829             98.496885   11755032.0  
830            226.197191     226651.0  
831            170.094175    8270000.0  

[300 rows x 13 columns]

In [21]:
selected_df.shape

(300, 13)

### 28.1.23

In [ ]:
# нужен пример конвейера

In [1]:
from models_functions import model_conveyor

In [2]:
import pandas as pd

In [14]:
pd.options.display.float_format = '{:_.2f}'.format

In [3]:
lien_df = pd.read_csv('../data/lien_df1_18_01_23.csv', sep=';')

In [4]:
selected_df = lien_df[['views', 'contact_name', 'seller_name', 'square', 'shown_by_days', 'distance', 'region_square', 'region_capital', 'grp', 'criminality', 'km_to_msk', 'km_to_region_capital', 'price_value']].copy()

In [5]:
selected_df = selected_df.dropna()  # пока поработаем без null

In [6]:
model, metrics_results, X_train_scaled, Y_train_scaled, X_test_scaled, Y_test_scaled, scaler_x_train, \
scaler_y_train, scaler_x_test, scaler_y_test = model_conveyor(selected_df, 'linear_regression', 'minmax', ['mape', 'mae', 'mse'], True)

100%|██████████| 3/3 [00:00<00:00, 738.17it/s]

mape
mae
mse


In [15]:
pd.DataFrame(metrics_results)

mape            mae  \
train_scaled               3_329_030_399_736.18           0.05   
test_scaled                4_637_483_987_513.11           0.21   
train_unscaled 1_498_063_679_861_379_825_664.00  23_255_381.68   
test_unscaled  2_318_741_993_612_866_224_128.00 102_736_016.09   

                                     mse  
train_scaled                        0.01  
test_scaled                         0.08  
train_unscaled  2_251_589_691_067_897.75  
test_unscaled  18_240_475_273_937_336.00

In [ ]:
# TODO
# на unscaled оценки - пиздец, надо внимательно проверить функцию, точно ли все ок делаем ну и в целом модель говно